/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemknowhow.human.guns;

/**
 *
 * @author Maneesh
 */
public enum TraitsOfHumanConsciousness {
    ACCEPTS_AUTHORITY,LOYAL,DEVOTED,ACCEPTS_WHATS_GIVEN,AFFECTIONATE,ASPIRING,AMBITIOUS,MOTIVATED,CANDID,CARING,CHANGE_ACCEPTS,EMBRACES
    ,CHEERFUL,CONSIDERATE,THOUGHTFUL,COOPERATIVE,COURAGEOUS,COURTEOUS,DECISIVE,DETERMINED,DOES_WHAT_IS_NECESSARY,RIGHT,
    PERSEVERES,ENDURES,ENTHUSIASTIC,EXPANSIVE,FAITH_IN_LIFE,FAITH_IN_ONESELF,FAITH_IN_OTHERS,FLEXIBLE,FORGIVING,FOCUSED,
    FREEDOM_GIVEN_TO_OTHERS,FRIENDLY,FRUGAL,THRIFTY,GENEROUS,GOODWILL,GRATEFUL,HARD_WORKING,HONEST,HUMBLE,INTERESTED,INVOLVED,JEALOUS,
    NOT,KIND,MATURE,MODEST,OPEN_MINDED,TOLERANT,OPTIMISTIC,PERFECTS,PERSISTENT,SUSTAINING,POSITIVE,PRACTICAL,PUNCTUAL,REALISTIC,
    RELIABLE,RESPECTFUL,RESPONSIBILITY,_TAKES_,RESPONSIBLE_,RESPONSIVE,SELF_CONFIDENT,SELF_DIRECTED,SELF_DISCIPLINED,
    SELF_ESTEEM,HIGH,SELF_GIVING,SELF_RELIANT,SELFLESS,SENSITIVE,SERIOUS,SINCERE,SOCIAL_INDEPENDENCE,SYMPATHETIC,SYSTEMATIC,
    TAKES_OTHERS_POINT_OF_VIEW,THOUGHTFUL_TOWARDS_OTHERS,TRUSTING,UNPRETENTIOUS,UNSELFISH,WILLING_DOES,WILLINGNESS,
    WORK_ORIENTED_,REBELLIOUS,IGNORES,REJECTS_WHATS_GIVEN,DISTANT,COLD,ALOOF,SELF_SATISFIED,UNMOTIVATED,CLOSED,GUARDED,
    SECRETIVE,UNCARING,UNFEELING,CALLOUS,REJECTS_CHANGE,CHEERLESS,GLOOMY,SOUR,GRUMPY,INCONSIDERATE,THOUGHTLESS,UNCOOPERATIVE,
    UNHELPFUL,COMBATIVE,COWERING,FEARFUL,RUDE,IMPOLITE,INDECISIVE,UNCOMMITTED,HOSTILE,UNSURE,
    DOES_WHAT_IS_CONVENIENT,RELENTS,GIVES_UP,UNENTHUSIASTIC,APATHETIC,INDIFFERENT,KEPT_BACK,TIGHT,CONSTRICTING,
    LIFE_CANT_BE_TRUSTED,LACK_OF_FAITH_IN_SELF,OTHERS_CANT_BE_RELIED_ON,INFLEXIBLE,RIGID,UNBENDING,STUBBORN,UNFORGIVING,
    RESENTFUL,SPITEFUL,UNFOCUSED,SCATTERED,AUTHORITARIAN,CONTROLLING,UNFRIENDLY,WASTEFUL,SPENDTHRIFT,
    STINGY,MISERLY,SELFISH,ILL_WILL,MALICE,HATRED,UNGRATEFUL,UNAPPRECIATIVE,LAZY,DISHONEST,DECEIVING,LYING,ARROGANT,CONCEITED,
    EGO_CENTRIC,COMPLACENT,ENVIOUS,COVETOUS,UNKIND,CRUEL,MEAN,IMMATURE,VAIN,
    NARROW,CLOSE,SMALL_MINDED,INTOLERANT,PESSIMISTIC,ALLOWS_IMPERFECTION,FLAGGING,FLEETING,UNSUSTAINING,NEGATIVE,IMPRACTICAL,
    NOT_VIABLE,LATE,NOT_ON_TIME,UNREALIST,UNRELIABLE,UNDEPENDABLE,DISRESPECTFUL,BLAMES_OTHERS,
    UNRESPONSIVE,UNRECEPTIVE,LACK_OF_SELF_CONFIDENCE,INSECURE,DIRECTED_BY_EXTERNALS,UNDISCIPLINED,UNRESTRAINED,
    INDULGENT,CONFIDENCE___LOW,SELF_CENTERED,DEPENDENT,INSENSITIVE,FRIVOLOUS,SILLY,TRIVIAL,
    INSINCERE,SOCIAL_APPROVAL_REQUIRED,UNSYMPATHETIC,UNSYSTEMATIC,DISORGANIZED,DISORDERLY,RANDOM,
    INSISTS_ON_OWN_VIEW,SUSPICIOUS,MISTRUSTING,PRETENTIOUS,AFFECTED,OSTENTATIOUS,
    UNWILLING,RELUCTANT,RECALCITRANT,CONVENIENCE_FIRST;
    
    public  int getPositiveAttitudesStart(){return 0;}
    public  int getPositiveAttitudesEnd(){return 85;}
    public  int getNegativeAttitudesStart(){return 87;}
    public  int getNegativeAttitudesEnd(){return 222;}
}
