/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemknowhow.humanactivity;

/**
 * http://en.wikipedia.org/wiki/Outline_of_relationships
 *
 * @author Maneesh
 */
public enum SocialActionTagFactory {

    CONFLICT_RESOLUTION,//
    HUMAN_BONDING,//
    INTERPERSONAL_COMMUNICATION,//
    PERSONAL_RELATIONSHIP_SKILLS,//
    RELATIONSHIP_EDUCATION,//
    SOCIAL_REJECTION,//
    WEDDING,//

    HUMAN_SEXUAL_ACTIVITY,//
    SEXUAL_INTERCOURSE,//
    SWINGING,//

    PERSONAL_ADVERTISEMENT,//
    MEET_MARKET,//
    FLIRTING,//
    PICK_UP_LINE,//
    SINGLES_EVENT,//
    COURTSHIP,//
    DATING,//
    INTERNET_DATING,//
    GOING_DUTCH,//
    ENDOGAMY,//_THE_PRACTICE_OF_MARRYING_WITHIN_A_SPECIFIC_ETHNIC_GROUP,//_CLASS,//_OR_SOCIAL_GROUP,//_REJECTING_ALL_OTHERS;_IN_CONTRAST_TO_EXOGAMY.
    HYPERGAMY,//_ACT_OR_PRACTICE_OF_SEEKING_A_SPOUSE_OF_HIGHER_SOCIOECONOMIC_STATUS,//_OR_CASTE_STATUS_THAN_ONESELF;[3]_IN_CONTRAST_TO_HYPOGAMY.

    DYSFUNCTIONAL_FAMILY,//
    RELATIONAL_TRANSGRESSION,//_VIOLATION_OF_IMPLICIT_OR_EXPLICIT_RELATIONAL_RULES.

    ABUSE,
    CHILD_ABUSE,//
    ELDER_ABUSE,//
    DATING_ABUSE,//
    DOMESTIC_VIOLENCE,//
    INFIDELITY,//_BREACH_OF_THE_EXPECTATION_OF_SEXUAL_EXCLUSIVITY._ALSO_CALLED_"CHEATING".
    EXTRAMARITAL_AFFAIR,//
    ADULTERY,//
    EXTRAMARITAL_SEX,//
    NAGGING,//
    SPOUSAL_ABUSE,//

    BREAKING_UP,//
    DIVORCE,//
    LEGAL_SEPARATION,//
    WIDOWHOOD,//

    DYSFUNCTIONAL_RELATIONS,//_SEE_DYSFUNCTIONAL_RELATIONS_SECTION_ABOVE.
    IRRECONCILABLE_DIFFERENCES,//

    ATTACHMENT_IN_ADULTS,//
    ATTACHMENT_IN_CHILDREN,//
    INTERPERSONAL_ATTRACTION,//_FORCE_ACTING_BETWEEN_TWO_PEOPLE_THAT_TENDS_TO_DRAW_THEM_TOGETHER_AND_RESIST_THEIR_SEPARATION,//_WHICH_LEADS_TO_FRIENDSHIPS_AND_ROMANTIC_RELATIONSHIPS._IT_IS_DISTINCT_FROM_PHYSICAL_ATTRACTION.
    NEW_RELATIONSHIP_ENERGY_,//(NRE),//_STATE_OF_MIND_EXPERIENCED_AT_THE_BEGINNING_OF_MOST_SIGNIFICANT_SEXUAL_AND_ROMANTIC_RELATIONSHIPS,//_TYPICALLY_INVOLVING_HEIGHTENED_EMOTIONAL_AND_SEXUAL_RECEPTIVITY_AND_EXCITEMENT._IT_BEGINS_WITH_THE_EARLIEST_ATTRACTIONS,//_GROWS_INTO_FULL_FORCE_WHEN_MUTUALITY_IS_ESTABLISHED,//_AND_SLOWLY_FADES_OVER_MONTHS_TO_YEARS.

    ACQUAINTANCE,//
    BUILDUP,//
    CONTINUATION,//
    DETERIORATION,//
    TERMINATION,//

    LOVE,//
    FAMILIAL_LOVE,//
    PARENTAL_LOVE,//
    MARITAL_LOVE,//
    BROTHERLY_LOVE,//
    FILIAL_PIETY,//
    VENERATION,//
    ROMANCE,//

    COMPERSION,//
    INTIMACY,//
    JEALOUSY,//
    LIMERENCE,//
    PASSION,//
    PLATONIC_LOVE,//
    PSYCHOLOGY_OF_SEXUAL_MONOGAMY,//
    UNCONDITIONAL_LOVE,//

    BISEXUAL,//
    HETEROSEXUAL,//
    HOMOSEXUAL,//
    ASEXUAL,//
    PANSEXUAL,//

    BOYFRIEND_GIRLFRIEND,
    CONFIDANT_OR_CONFIDANTE,
    FAMILY_MEMBER,
    FRIEND_OR_COMPANION,
    LIFE_PARTNER,
    SPOUSE,
    MISTRESS,
    SOULMATE,//
    SIGNIFICANT_OTHER,
    SEXUAL_PARTNER,//

    BRIDE_PRICE,//
    DOWER,//
    DOWRY,//
    BRIDESERVICE,//
    LOVE_CONTRACT,//

    FAMILY_THERAPY,//
    RELATIONSHIP_COUNSELING,//

    PEOPLE_SKILLS,//
    COMMUNICATIONS_TRAINING,//
    EMOTIONAL_INTELLIGENCE,//
    EMOTIONAL_LITERACY,//
    SOCIAL_INTELLIGENCE,//
    SOCIAL_SKILLS,//

    SPINSTER,//
    CELIBATE,//

    PET_NAMES,
    FACE_TO_FACE,
    LOVE_LETTER,
    TELEPHONE,
    INTERNET_ROMANCE,
    ROMANTICISM,
    POETRY,
    DRAWING,
    PAINTING,
    COOKING,
    COUPLE_DANCING,
    MOVIES,
    STARGAZING,
    SERENADE,
    PHYSICAL_INTIMACY,
    TOUCHING,
    EROGENOUS_ZONES,
    CUDDLING,
    ARM_AROUND_SHOULDER,
    ARMS_AROUND_ABDOMEN,
    HEAD_ON_SHOULDER,
    HEAD_ON_LAP,
    HUGGING,
    EYE_CONTACT,
    HOLDING_HANDS,
    KISSING,
    NUZZLING,
    EMOTIONAL_INTIMACY,
    ACCEPTANCE,
    EMPATHY,
    SYMPATHY,
    LONGING,
    EMOTIONAL_CONTAGION,//_TENDENCY_TO_CATCH_AND_FEEL_EMOTIONS_THAT_ARE_SIMILAR_TO_AND_INFLUENCED_BY_THOSE_OF_OTHERS.
    CASUAL_RELATIONSHIP,//_SEXUAL_RELATIONSHIP_WITHOUT_THE_EXTRA_COMMITMENTS_OF_A_MORE_FORMAL_ROMANTIC_RELATIONSHIP.
    RELATIONAL_DISORDER,//_MENTAL_DISORDER_ATTRIBUTABLE_TO_A_RELATIONSHIP_RATHER_THAN_TO_ANY_ONE_INDIVIDUAL_IN_THE_RELATIONSHIP.
    EMOTIONAL_TYRANNY,//
    EQUAL_POWER_RELATIONSHIP,//
    FEAR_OF_COMMITMENT,//
    FRIEND_ZONE,//
    INTERNET_RELATIONSHIP,//
    QUALITY_TIME,//
    RECIPROCAL_LIKING,//
    RESPECT,//
    SEXUAL_CAPITAL,//
    TERM_OF_ENDEARMENT,//
    ROOMMATE,//

    BROKEN_HEART,//
    LONG_DISTANCE_RELATIONSHIP,//
    MARRIAGE,//_A_SOCIALLY_BINDING_COMMITMENT_TO_A_PARTNER
    FEMALE_LED_RELATIONSHIP,//_ROMANTIC_COMMITMENT_WHERE_THE_WOMAN_IS_THE_LEAD_AND/OR_PRINCIPLE_PARTNER;_OFTEN_REFERRED_TO_AS_AN_FLR
    SEXUAL_INFIDELITY,//_HAVING_A_SEXUAL_RELATIONSHIP_OUTSIDE_OF_A_RELATIONSHIP_THAT_INCLUDES_A_COMMITMENT_TO_HAVE_NO_OTHER_SEXUAL_PARTNERS
    SEXUAL_FIDELITY,//_NOT_HAVING_OTHER_SEXUAL_PARTNERS_OTHER_THAN_ONE'S_COMMITTED_PARTNER,//_EVEN_TEMPORARILY
    SERIAL_MONOGAMY,//_HAVING_A_SERIES_OF_MONOGAMOUS_RELATIONSHIPS,//_ONE_AFTER_THE_OTHER
    POLYAMORY,//_ENCOMPASSES_A_WIDE_RANGE_OF_RELATIONSHIPS,//_INCLUDING_THOSE_ABOVE:_POLYAMOROUS_RELATIONSHIPS_MAY_INCLUDE_BOTH_COMMITTED_AND_CASUAL_RELATIONSHIPS
    RELATIONSHIP_ANARCHY,//_A_THEORY_THAT_QUESTIONS_THE_IDEA_OF_LOVE_AS_A_SPECIAL,//_LIMITED_FEELING_THAT_IS_ONLY_REAL_IF_IT_IS_RESTRICTED_TO_TWO_PEOPLE_ONLY,//_AT_ANY_GIVEN_MOMENT.
    SEXUAL_PROMISCUITY,//_HAVING_CASUAL_SEXUAL_PARTNERS_AT_WILL_(COMPARE_WITH_CHASTITY)
    AFFECTION,//
    CASUAL_DATING,//
    KISS,//
    KISSING_TRADITIONS,//

    FEMALE_BONDING,//

    LIMBIC_REGULATION,//
    LIMBIC_RESONANCE,//
    LIMBIC_REVISION,//
    MHC_IN_SEXUAL_MATE_SELECTION,//

}
