/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemknowhow.humanactivity;

/**
 *
 * @author Maneesh
 */
public enum VerbTagFactory {
A,ABIDE,ACCELERATE,ACCEPT,ACCOMPLISH,ACHIEVE,ACQUIRE,ACTED,ACTIVATE,ADAPT,ADD,ADDRESS,ADMINISTER,ADMIRE,ADMIT,ADOPT,ADVISE,AFFORD,
AGREE,ALERT,ALIGHT,ALLOW,ALTERED,AMUSE,ANALYZE,ANNOUNCE,ANNOY,ANSWER,ANTICIPATE,APOLOGIZE,APPEAR,APPLAUD,APPLIED,APPOINT,APPRAISE,
APPRECIATE,APPROVE,ARBITRATE,ARGUE,ARISE,ARRANGE,ARREST,ARRIVE,ASCERTAIN,ASK,ASSEMBLE,ASSESS,ASSIST,ASSURE,ATTACH,ATTACK,ATTAIN,
ATTEMPT,ATTEND,ATTRACT,AUDITED,AVOID,AWAKE,B,BACK,BAKE,BALANCE,BAN,BANG,BARE,BAT,BATHE,BATTLE,BE,BEAM,BEAR,BEAT,BECOME,BEG,BEGIN,
BEHAVE,BEHOLD,BELONG,BEND,BESET,BET,BID,BIND,BITE,BLEACH,BLEED,BLESS,BLIND,BLINK,BLOT,BLOW,BLUSH,BOAST,BOIL,BOLT,BOMB,BOOK,BORE,
BORROW,BOUNCE,BOW,BOX,BRAKE,BRANCH,BREAK,BREATHE,BREED,BRIEF,BRING,BROADCAST,BRUISE,BRUSH,BUBBLE,BUDGET,BUILD,BUMP,BURN,BURST,BURY,
BUST,BUY,BUZZ,C,CALCULATE,CALL,CAMP,CARE,CARRY,CARVE,CAST,CATALOG,CATCH,CAUSE,CHALLENGE,CHANGE,CHARGE,CHART,CHASE,CHEAT,CHECK,CHEER,
CHEW,CHOKE,CHOOSE,CHOP,CLAIM,CLAP,CLARIFY,CLASSIFY,CLEAN,CLEAR,CLING,CLIP,CLOSE,CLOTHE,COACH,COIL,COLLECT,COLOR,COMB,COME,COMMAND,
COMMUNICATE,COMPARE,COMPETE,COMPILE,COMPLAIN,COMPLETE,COMPOSE,COMPUTE,CONCEIVE,CONCENTRATE,CONCEPTUALIZE,CONCERN,CONCLUDE,CONDUCT,
CONFESS,CONFRONT,CONFUSE,CONNECT,CONSERVE,CONSIDER,CONSIST,CONSOLIDATE,CONSTRUCT,CONSULT,CONTAIN,CONTINUE,CONTRACT,CONTROL,CONVERT,
COORDINATE,COPY,CORRECT,CORRELATE,COST,COUGH,COUNSEL,COUNT,COVER,CRACK,CRASH,CRAWL,CREATE,CREEP,CRITIQUE,CROSS,CRUSH,CRY,CURE,CURL,
CURVE,CUT,CYCLE,D,DAM,DAMAGE,DANCE,DARE,DEAL,DECAY,DECEIVE,DECIDE,DECORATE,DEFINE,DELAY,DELEGATE,DELIGHT,DELIVER,DEMONSTRATE,DEPEND,
DESCRIBE,DESERT,DESERVE,DESIGN,DESTROY,DETAIL,DETECT,DETERMINE,DEVELOP,DEVISE,DIAGNOSE,DIG,DIRECT,DISAGREE,DISAPPEAR,DISAPPROVE,
DISARM,DISCOVER,DISLIKE,DISPENSE,DISPLAY,DISPROVE,DISSECT,DISTRIBUTE,DIVE,DIVERT,DIVIDE,DO,DOUBLE,DOUBT,DRAFT,DRAG,DRAIN,DRAMATIZE,
DRAW,DREAM,DRESS,DRINK,DRIP,DRIVE,DROP,DROWN,DRUM,DRY,DUST,DWELL,E,EARN,EAT,EDITED,EDUCATE,ELIMINATE,EMBARRASS,EMPLOY,EMPTY,ENACTED,
ENCOURAGE,END,ENDURE,ENFORCE,ENGINEER,ENHANCE,ENJOY,ENLIST,ENSURE,ENTER,ENTERTAIN,ESCAPE,ESTABLISH,ESTIMATE,EVALUATE,EXAMINE,EXCEED,
EXCITE,EXCUSE,EXECUTE,EXERCISE,EXHIBIT,EXIST,EXPAND,EXPECT,EXPEDITE,EXPERIMENT,EXPLAIN,EXPLODE,EXPRESS,EXTEND,EXTRACT,F,FACE,
FACILITATE,FADE,FAIL,FANCY,FASTEN,FAX,FEAR,FEED,FEEL,FENCE,FETCH,FIGHT,FILE,FILL,FILM,FINALIZE,FINANCE,FIND,FIRE,FIT,FIX,FLAP,FLASH,
FLEE,FLING,FLOAT,FLOOD,FLOW,FLOWER,FLY,FOLD,FOLLOW,FOOL,FORBID,FORCE,FORECAST,FOREGO,FORESEE,FORETELL,FORGET,FORGIVE,FORM,FORMULATE,
FORSAKE,FRAME,FREEZE,FRIGHTEN,FRY,G,GATHER,GAZE,GENERATE,GET,GIVE,GLOW,GLUE,GO,GOVERN,GRAB,GRADUATE,GRATE,GREASE,GREET,GRIN,GRIND,GRIP,
GROAN,GROW,GUARANTEE,GUARD,GUESS,GUIDE,H,HAMMER,HAND,HANDLE,HANDWRITE,HANG,HAPPEN,HARASS,HARM,HATE,HAUNT,HEAD,HEAL,HEAP,HEAR,HEAT,HELP,
HIDE,HIT,HOLD,HOOK,HOP,HOPE,HOVER,HUG,HUM,HUNT,HURRY,HURT,HYPOTHESIZE,I,IDENTIFY,IGNORE,ILLUSTRATE,IMAGINE,IMPLEMENT,IMPRESS,
IMPROVE,IMPROVISE,INCLUDE,INCREASE,INDUCE,INFLUENCE,INFORM,INITIATE,INJECT,INJURE,INLAY,INNOVATE,INPUT,INSPECT,INSPIRE,INSTALL,
INSTITUTE,INSTRUCT,INSURE,INTEGRATE,INTEND,INTENSIFY,INTEREST,INTERFERE,INTERLAY,INTERPRET,INTERRUPT,INTERVIEW,INTRODUCE,INVENT,
INVENTORY,INVESTIGATE,INVITE,IRRITATE,ITCH,J,JAIL,JAM,JOG,JOIN,JOKE,JUDGE,JUGGLE,JUMP,JUSTIFY,K,KEEP,KEPT,KICK,KILL,KISS,KNEEL,KNIT,
KNOCK,KNOT,KNOW,L,LABEL,LAND,LAST,LAUGH,LAUNCH,LAY,LEAD,LEAN,LEAP,LEARN,LEAVE,LECTURE,LED,LEND,LET,LEVEL,LICENSE,LICK,LIE,LIFTED,
LIGHT,LIGHTEN,LIKE,LIST,LISTEN,LIVE,LOAD,LOCATE,LOCK,LOG,LONG,LOOK,LOSE,LOVE,M,MAINTAIN,MAKE,MAN,MANAGE,MANIPULATE,MANUFACTURE,MAP,
MARCH,MARK,MARKET,MARRY,MATCH,MATE,MATTER,MEAN,MEASURE,MEDDLE,MEDIATE,MEET,MELT,MEMORIZE,MEND,MENTOR,MILK,MINE,MISLEAD,MISS,MISSPELL,
MISTAKE,MISUNDERSTAND,MIX,MOAN,MODEL,MODIFY,MONITOR,MOOR,MOTIVATE,MOURN,MOVE,MOW,MUDDLE,MUG,MULTIPLY,MURDER,N,NAIL,NAME,NAVIGATE,NEED,
NEGOTIATE,NEST,NOD,NOMINATE,NORMALIZE,NOTE,NOTICE,NUMBER,O,OBEY,OBJECT,OBSERVE,OBTAIN,OCCUR,OFFEND,OFFER,OFFICIATE,OPEN,OPERATE,ORDER,
ORGANIZE,ORIENTED,ORIGINATE,OVERCOME,OVERDO,OVERDRAW,OVERFLOW,OVERHEAR,OVERTAKE,OVERTHROW,OWE,OWN,P,PACK,PADDLE,PAINT,PARK,PART,
PARTICIPATE,PASS,PASTE,PAT,PAUSE,PAY,PECK,PEDAL,PEEL,PEEP,PERCEIVE,PERFECT,PERFORM,PERMIT,PERSUADE,PHONE,PHOTOGRAPH,PICK,PILOT,PINCH,
PINE,PINPOINT,PIONEER,PLACE,PLAN,PLANT,PLAY,PLEAD,PLEASE,PLUG,POINT,POKE,POLISH,POP,POSSESS,POST,POUR,PRACTICE,PRAISED,PRAY,PREACH,
PRECEDE,PREDICT,PREFER,PREPARE,PRESCRIBE,PRESENT,PRESERVE,PRESET,PRESIDE,PRESS,PRETEND,PREVENT,PRICK,PRINT,PROCESS,PROCURE,PRODUCE,
PROFESS,PROGRAM,PROGRESS,PROJECT,PROMISE,PROMOTE,PROOFREAD,PROPOSE,PROTECT,PROVE,PROVIDE,PUBLICIZE,PULL,PUMP,PUNCH,PUNCTURE,PUNISH,
PURCHASE,PUSH,PUT,Q,QUALIFY,QUESTION,QUEUE,QUIT,R,RACE,RADIATE,RAIN,RAISE,RANK,RATE,REACH,READ,REALIGN,REALIZE,REASON,RECEIVE,
RECOGNIZE,RECOMMEND,RECONCILE,RECORD,RECRUIT,REDUCE,REFER,REFLECT,REFUSE,REGRET,REGULATE,REHABILITATE,REIGN,REINFORCE,REJECT,
REJOICE,RELATE,RELAX,RELEASE,RELY,REMAIN,REMEMBER,REMIND,REMOVE,RENDER,REORGANIZE,REPAIR,REPEAT,REPLACE,REPLY,REPORT,REPRESENT,
REPRODUCE,REQUEST,RESCUE,RESEARCH,RESOLVE,RESPOND,RESTORED,RESTRUCTURE,RETIRE,RETRIEVE,RETURN,REVIEW,REVISE,RHYME,RID,RIDE,RING,
RINSE,RISE,RISK,ROB,ROCK,ROLL,ROT,RUB,RUIN,RULE,RUN,RUSH,S,SACK,SAIL,SATISFY,SAVE,SAW,SAY,SCARE,SCATTER,SCHEDULE,SCOLD,SCORCH,SCRAPE,
SCRATCH,SCREAM,SCREW,SCRIBBLE,SCRUB,SEAL,SEARCH,SECURE,SEE,SEEK,SELECT,SELL,SEND,SENSE,SEPARATE,SERVE,SERVICE,SET,SETTLE,SEW,SHADE,
SHAKE,SHAPE,SHARE,SHAVE,SHEAR,SHED,SHELTER,SHINE,SHIVER,SHOCK,SHOE,SHOOT,SHOP,SHOW,SHRINK,SHRUG,SHUT,SIGH,SIGN,SIGNAL,SIMPLIFY,SIN,
SING,SINK,SIP,SIT,SKETCH,SKI,SKIP,SLAP,SLAY,SLEEP,SLIDE,SLING,SLINK,SLIP,SLIT,SLOW,SMASH,SMELL,SMILE,SMITE,SMOKE,SNATCH,SNEAK,SNEEZE,
SNIFF,SNORE,SNOW,SOAK,SOLVE,SOOTHE,SOOTHSAY,SORT,SOUND,SOW,SPARE,SPARK,SPARKLE,SPEAK,SPECIFY,SPEED,SPELL,SPEND,SPILL,SPIN,SPIT,SPLIT,
SPOIL,SPOT,SPRAY,SPREAD,SPRING,SPROUT,SQUASH,SQUEAK,SQUEAL,SQUEEZE,STAIN,STAMP,STAND,STARE,START,STAY,STEAL,STEER,STEP,STICK,
STIMULATE,STING,STINK,STIR,STITCH,STOP,STORE,STRAP,STREAMLINE,STRENGTHEN,STRETCH,STRIDE,STRIKE,STRING,STRIP,STRIVE,STROKE,STRUCTURE,
STUDY,STUFF,SUBLET,SUBTRACT,SUCCEED,SUCK,SUFFER,SUGGEST,SUIT,SUMMARIZE,SUPERVISE,SUPPLY,SUPPORT,SUPPOSE,SURPRISE,SURROUND,SUSPECT,
SUSPEND,SWEAR,SWEAT,SWEEP,SWELL,SWIM,SWING,SWITCH,SYMBOLIZE,SYNTHESIZE,SYSTEMIZE,T,TABULATE,TAKE,TALK,TAME,TAP,TARGET,TASTE,TEACH,
TEAR,TEASE,TELEPHONE,TELL,TEMPT,TERRIFY,TEST,THANK,THAW,THINK,THRIVE,THROW,THRUST,TICK,TICKLE,TIE,TIME,TIP,TIRE,TOUCH,TOUR,TOW,TRACE,
TRADE,TRAIN,TRANSCRIBE,TRANSFER,TRANSFORM,TRANSLATE,TRANSPORT,TRAP,TRAVEL,TREAD,TREAT,TREMBLE,TRICK,TRIP,TROT,TROUBLE,TROUBLESHOOT,
TRUST,TRY,TUG,TUMBLE,TURN,TUTOR,TWIST,TYPE,U,UNDERGO,UNDERSTAND,UNDERTAKE,UNDRESS,UNFASTEN,UNIFY,UNITE,UNLOCK,UNPACK,UNTIDY,UPDATE,
UPGRADE,UPHOLD,UPSET,USE,UTILIZE,V,VANISH,VERBALIZE,VERIFY,VEX,VISIT,W,WAIL,WAIT,WAKE,WALK,WANDER,WANT,WARM,WARN,WASH,WASTE,WATCH,
WATER,WAVE,WEAR,WEAVE,WED,WEEP,WEIGH,WELCOME,WEND,WET,WHINE,WHIP,WHIRL,WHISPER,WHISTLE,WIN,WIND,WINK,WIPE,WISH,WITHDRAW,WITHHOLD,
WITHSTAND,WOBBLE,WONDER,WORK,WORRY,WRAP,WRECK,WRESTLE,WRIGGLE,WRING,WRITE,X_RAY,YAWN,YELL,ZIP,ZOOM;
}
